//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quan_li_thuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public cart()
        {
            this.cart_items = new HashSet<cart_items>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> total_items { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual ICollection<cart_items> cart_items { get; set; }
        public virtual user user { get; set; }
    }
}
