//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quan_li_thuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon
    {
        public coupon()
        {
            this.coupon_conditions = new HashSet<coupon_conditions>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual ICollection<coupon_conditions> coupon_conditions { get; set; }
    }
}
