//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quan_li_thuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class district
    {
        public district()
        {
            this.wards = new HashSet<ward>();
        }
    
        public string code { get; set; }
        public string name { get; set; }
        public string name_en { get; set; }
        public string full_name { get; set; }
        public string full_name_en { get; set; }
        public string code_name { get; set; }
        public string province_code { get; set; }
    
        public virtual province province { get; set; }
        public virtual ICollection<ward> wards { get; set; }
    }
}
